safe_mode = Off
open_basedir =
allow_url_include = On
php_flag allow_url_fopen on
mssql.textlimit = 2147483647
mssql.textsize = 2147483647

extension=pdo.so
extension=pdo_sqlite.so
extension=pdo_mysql.so
extension=sqlite.so

;   - Show all errors, except for notices
;
error_reporting = E_ALL & ~E_NOTICE

;   - Toggle display errors on the page
;
display_errors = Off
